### ISSUE TITLE
leafy background

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/pastesafe#1]
add this to css to make it [pretty](https://unsplash.com/photos/ALu2B7Vy7ao)

```css
html {
  background:
    linear-gradient(-120deg, #496d51ee, #013a0dff),
    url(https://source.unsplash.com/ALu2B7Vy7ao),
    #013a0dff;
  background-size: cover;
}
```

**Comment by chase-moskal** [comment]
also consider

```css
body {
  backdrop-filter: blur(20px);
}

.siteheader {
  background: #ffffff11;
}
```
